name: my_nbooks
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.9
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - seaborn
  - git